modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="sharedbackpack"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.sharedbackpack]]
modId="forge"
mandatory=true
versionRange="[47.4.10,)"
ordering="NONE"
side="BOTH"
